# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockclimb', '0002_climb_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img/art'),
            preserve_default=False,
        ),
    ]
