# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockclimb', '0005_auto_20160415_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
