# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockclimb', '0006_auto_20160415_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='image',
            field=models.ImageField(blank=True, upload_to='wsgi/media/img'),
        ),
    ]
