# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockclimb', '0008_auto_20160415_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
