# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockclimb', '0009_auto_20160411_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='image',
            field=models.ImageField(upload_to='rockclimb/static/img'),
        ),
    ]
