# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockclimb', '0014_auto_20160411_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
