# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockclimb', '0015_auto_20160412_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climb',
            name='user',
        ),
    ]
