# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockclimb', '0015_auto_20160412_1724'),
        ('rockclimb', '0017_auto_20160412_1630'),
    ]

    operations = [
    ]
